### PR TITLE
Update product_backlog.md

### PR DESCRIPTION
**Pull request by guilhermedelyra**

### CODE REVIEW

**Comment by rafaelmakaha** [comment]
This PR closes #15

**Comment by rafaelmakaha** [comment]
Removed merge commit
Added US46

**Review by rafaelmakaha — APPROVED** [review]
Removed merge commit
Added US45

Very good backlog table!

**Review by joaovitorml — APPROVED** [review]

**Review by joaovitorml — CHANGES_REQUESTED** [review]
Precisamos atualizar novamente o backlog com as histórias relacionadas a Metas e Marketplace

**Review by joaovitorml — CHANGES_REQUESTED** [review]
- [x] Adicionar histórias relacionadas a Metas e Marketplace

**Comment by guilhermedelyra** [comment]
resolves: #16 #36

**Review by joaovitorml — APPROVED** [review]
gostei e aprovei

**Pull request merged**
